export function navyBF(gender, height, waist, neck, hips) {
  if (!height || !waist || !neck) return null
  height = parseFloat(height)
  waist = parseFloat(waist)
  neck = parseFloat(neck)
  hips = parseFloat(hips || 0)
  if (gender === 'female') {
    if (!hips) return null
    const bf = 163.205 * Math.log10(waist + hips - neck) - 97.684 * Math.log10(height) - 78.387
    return Math.max(0, Math.round(bf * 10) / 10)
  } else {
    const bf = 86.010 * Math.log10(waist - neck) - 70.041 * Math.log10(height) + 36.76
    return Math.max(0, Math.round(bf * 10) / 10)
  }
}

export function bfCategory(bf, gender) {
  if (gender === 'female') {
    if (bf < 14) return 'Essential fat'
    if (bf < 21) return 'Athletic'
    if (bf < 25) return 'Fitness'
    if (bf < 32) return 'Average'
    return 'Above average'
  } else {
    if (bf < 6) return 'Essential fat'
    if (bf < 14) return 'Athletic'
    if (bf < 18) return 'Fitness'
    if (bf < 25) return 'Average'
    return 'Above average'
  }
}

export function initials(name) {
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
}

export function goalColor(goal) {
  return { 'Fat loss': '#ffb84d', 'Muscle building': '#4dff91', 'Recomp': '#4da6ff' }[goal] || '#4da6ff'
}

export function fmtDelta(cur, prev, invertColor = false) {
  if (prev == null) return null
  const d = Math.round((cur - prev) * 10) / 10
  if (d === 0) return { text: '—', color: '#555' }
  const positive = invertColor ? d < 0 : d > 0
  return { text: (d > 0 ? '+' : '') + d, color: positive ? '#4dff91' : '#ff4d4d' }
}

export function generateReport(client, plan, checkins) {
  const last = checkins.length ? checkins[checkins.length - 1] : null
  const first = checkins.length ? checkins[0] : null
  const startW = first ? first.weight : client.start_weight
  const curW = last ? last.weight : client.start_weight
  const change = Math.round((curW - startW) * 10) / 10

  return `LT COACHING — CLIENT REPORT
────────────────────────────
Client: ${client.name}
Goal: ${client.goal}
Program: Week ${checkins.length} of ${client.weeks}

BODY METRICS
Start weight: ${startW} kg
Current weight: ${curW} kg
Change: ${change > 0 ? '+' : ''}${change} kg
Target weight: ${client.target_weight} kg
${last && last.bf != null ? `Current body fat: ${last.bf}%\nBF category: ${bfCategory(last.bf, client.gender)}` : ''}
${last && last.waist ? `Waist: ${last.waist} cm` : ''}${last && last.neck ? `\nNeck: ${last.neck} cm` : ''}${last && last.hips && client.gender === 'female' ? `\nHips: ${last.hips} cm` : ''}

DAILY NUTRITION TARGETS
Calories: ${client.calories} kcal
Protein: ${client.protein}g
Carbohydrates: ${client.carbs}g
Fats: ${client.fats}g

${checkins.length ? `CHECK-IN HISTORY\n${checkins.map(ci => `Week ${ci.week}: ${ci.weight}kg${ci.bf != null ? ` · ${ci.bf}% BF` : ''}`).join('\n')}` : ''}

${plan ? `MEAL PLAN: ${plan.name}\n${plan.meals.map((m, i) => `Meal ${i + 1}: ${m.name} — ${m.calories} kcal | P:${m.protein}g C:${m.carbs}g F:${m.fats}g`).join('\n')}` : 'No meal plan assigned.'}

${client.notes ? `COACH NOTES\n${client.notes}` : ''}

────────────────────────────
Generated by LT Coaching
`
}
